define link_target
$(call add_target_link)

$(TARGET_NAME)_LINK_TYPE := $(TARGET_TYPE)
$(TARGET_NAME)_LINK_DIR = $(if $(TARGET_LINK_DIR), $(TARGET_LINK_DIR), $($(TARGET_NAME)_OBJ_DIR))
$(TARGET_NAME)_LINK_FILES = $$(if $$(strip $$($(TARGET_NAME)_LINK_DIR)), $$(wildcard $$($(TARGET_NAME)_LINK_DIR)/*)) $(TARGET_LINK_FILES) 

$(TARGET_NAME)_LINKER_FLAGS := $(if $(TARGET_LINKER_FLAGS), $(TARGET_LINKER_FLAGS), $(LINKER_FLAGS)) \
								$(if $(filter $$($$(TARGET_NAME)_LINK_TYPE), SHARED), -shared -fPIC, )

$(TARGET_NAME)_LINK_DEPS := $(TARGET_LINK_DEPS)

$(TARGET_NAME)_OUT_DIR := $(if $(TARGET_OUT_DIR), $(TARGET_OUT_DIR), $(OUT_DIR)/$(TARGET_NAME))/
$(TARGET_NAME)_OUT_FILE := $$($(TARGET_NAME)_OUT_DIR)/$(TARGET_PREFIX)$(TARGET_NAME)$(TARGET_SUFFIX)

.PHONY: $(TARGET_NAME) $(TARGET_NAME)_link_msg

$(if $(filter $(TARGET_TYPE),EXEC),\
	$$(eval PHONY.: $(TARGET_NAME)_run)\
	$$(eval $(TARGET_NAME)_run: $(TARGET_NAME) ; ./$$($(TARGET_NAME)_OUT_FILE) $(subst ",,$(ARGS))))

$(TARGET_NAME): $$($(TARGET_NAME)_LINK_DEPS) $(TARGET_NAME)_link

$(TARGET_NAME)_compile:

$(TARGET_NAME)_link: $(TARGET_NAME)_compile $$($(TARGET_NAME)_LINK_FILES) $(TARGET_NAME)_link_msg $$($(TARGET_NAME)_OUT_DIR)  $$($(TARGET_NAME)_OUT_FILE)
	
$(TARGET_NAME)_link_msg:
	@printf "$(STATUS_MSG_PREFIX) Linking $(TARGET_NAME)...\n"

$$($(TARGET_NAME)_OUT_FILE): $$($(TARGET_NAME)_LINK_FILES) 
	$(if $(filter $(TARGET_TYPE), STATIC),\
	ar rcs $$@ $$($(TARGET_NAME)_LINKER_FLAGS) $$($(TARGET_NAME)_LINK_FILES), \
	g++ -o $$@ $$($(TARGET_NAME)_LINK_FILES)) $$($(TARGET_NAME)_LINKER_FLAGS)

endef
